### ISSUE TITLE
All vesting balances are showing up as BTS

### ISSUE THREAD

**Issue by HarukaMa** [oxarbitrage/bitshares-explorer#14]
... while they could be any asset, especially with crypto-bridge's coin staking this is very apparent.

**Comment by oxarbitrage** [comment]
thank you adding the issue, can you send me the link to the account so i can fix and compare ?

thanks.

**Comment by HarukaMa** [comment]
http://open-explorer.io/#/accounts/1.2.21561

This is my account, but it seems the explorer is down right now.

**Comment by oxarbitrage** [comment]
thanks, explorer up now and fixing the issue.

**Comment by oxarbitrage** [comment]
was fixed in the 2 versions, thank you very much for the bug report:

http://open-explorer.io/#/accounts/1.2.21561
http://bitshares-explorer.io/#/accounts/1.2.21561

**Comment by HarukaMa** [comment]
It seems that something is still not right:

`5,117.949 BTS - 1.13.2952 , 51,179.488 ARCOIN - 1.13.2952 , 51.179 BRIDGE.BCO - 1.13.2952`

**Comment by oxarbitrage** [comment]
now sure what is wrong, can you explain pls ?

**Comment by HarukaMa** [comment]
1. all object ids are the same, which is apparently not correct;
2. all numbers are 51179488, which is also not correct.

Seems that all values are coming from the last vesting balance, instead of individuals.

**Comment by oxarbitrage** [comment]
silly me, sorry about that. pls check now, its fixed.
